const usersTable = `CREATE TABLE IF NOT EXISTS users (
  staff_id SERIAL PRIMARY KEY,
  firstname VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  age INT NOT NULL,
  password VARCHAR(100) NOT NULL,
  date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(100) NOT NULL,
  gender VARCHAR(100) NOT NULL,
  role VARCHAR(100) NOT NULL
);`;
